VERSION = '0.1.01'
# ModBus/TCP
MODBUS_PORT = 502
# Modbus mode
MODBUS_TCP = 1
MODBUS_RTU = 2

READ_GROUP_COILS = 0x01
READ_GROUP_DISCRETE_COILS = 0x02
READ_GROUP_HOLDING_REGISTERS = 0x03
READ_GROUP_INPUT_REGISTERS = 0x04
WRITE_SINGLE_HOLDING_REGISTERS = 0x06
WRITE_GROUP_COILS = 0x0F
WRITE_GROUP_HOLDING_REGISTERS = 0x10