"""
Modbus function read/write
"""
READ_GROUP_COILS = 0x01
READ_GROUP_DISCRETE_COILS = 0x02
READ_GROUP_HOLDING_REGISTERS = 0x03
READ_GROUP_INPUT_REGISTERS = 0x04
WRITE_SINGLE_HOLDING_REGISTERS = 0x06
WRITE_GROUP_COILS = 0x0F
WRITE_GROUP_HOLDING_REGISTERS = 0x10

